Book/urls.py
from django.urls import path
from .views import toggle_like
from . import views


app_name = 'Book'
urlpatterns = [
    path('', views.index, name='index'),
    path('sign-up/', views.register, name='sign_up'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('book-detail/<int:pk>/',views.book_detail,name='book_detail'), 
    path('delete-comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('book/like/<int:pk>/', views.toggle_like, name='toggle_like'),
    path('add/', views.add_book, name='add_book'),
    path('edit/<int:pk>/', views.edit_book, name='edit_book'),
    path('delete/<int:pk>/', views.delete_book, name='delete_book'),
]

bookms/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Book.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
{% load static %}

<header class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <div class="container">
        <h1 class="navbar-brand">
            <a href="{% url 'Book:index' %}" class="text-decoration-none" style="font-family: 'IRANSans', sans-serif; font-size: 2rem; font-weight: bold; color: #007bff;">
                <i class="fas fa-book mr-2"></i>کتابخانه آنلاین
            </a>
        </h1>
        <nav class="ml-auto">
            {% if not request.user.is_authenticated %}
                <a href="{% url 'Book:sign_up' %}" class="btn btn-primary btn-lg mx-3">
                    <i class="fas fa-sign-in-alt mr-2"></i>ثبت نام
                </a>
                <a href="{% url 'Book:login' %}" class="btn btn-primary btn-lg mx-3">
                    <i class="fas fa-sign-out-alt mr-2"></i>ورود
                </a>
            {% else %}
                <a href="{% url 'Book:logout' %}" class="btn btn-danger btn-lg mx-3">
                    <i class="fas fa-sign-out-alt mr-2"></i>خروج
                </a>
            {% endif %}
        </nav>
    </div>
</header>

templates/includes/header_links.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
    	
    {% endblock %}</title>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</head>